# The Shufffle Game

#### A very basic game to demonstrate use of numpy arrays and shuffle.

*The game starts with a random generated number grid shown to the user. The grid is shuffled and the user is asked to find one of the numbers*

#### Import libraries ####

In [78]:
import numpy as np
from numpy import random

#### Generate random grid of numbers

In [79]:
grid = np.random.randint(10, size=(3,3))
grid

array([[3, 4, 9],
       [4, 8, 9],
       [0, 7, 3]])

#### Present grid to user

In [80]:
print("Welcome to Shuffle! Here are your numbers...\n")
for i in grid:
    print(i)

print("\nShuffling grid...")


Welcome to Shuffle! Here are your numbers...

[3 4 9]
[4 8 9]
[0 7 3]

Shuffling grid...


#### Shuffle grid

In [81]:
random.shuffle(grid[0])
random.shuffle(grid[1])
random.shuffle(grid[2])

#### Get users column selection

In [82]:
print("The grid is now shuffled!")

The grid is now shuffled!


In [83]:
# Run the game...

activeGame = True

while(activeGame):
    column = int(input("Pick a column: "))
    column = column - 1
    row = int(input("\nPick a row: "))
    row = row -1
    
    guess = int(input("\nGuess the number: "))
    
    if(grid[row][column] == guess):
        print("\nCorrect! You guessed the number was {one} correctly.".format(one=guess))
        activeGame = False
        break

        print("\nTry again...\n")
        column = int(input("Pick a column: "))
        column = column - 1
        row = int(input("\nPick a row: "))
        row = row -1
        guess = int(input("\nGuess the number: "))

        
print("\nShuffled grid.\n")
for i in grid:
    print(i)

Pick a column: 2

Pick a row: 3

Guess the number: 0

Correct! You guessed the number was 0 correctly.

Shuffled grid.

[9 4 3]
[8 4 9]
[7 0 3]
