# The Shufffle Game

#### A very basic game to demonstrate use of numpy arrays and shuffle.

*The game starts with a random generated number grid shown to the user. The grid is shuffled and the user is asked to find one of the numbers*

#### Import libraries ####

In [1]:
import numpy as np
from numpy import random

#### Generate random grid of numbers

In [2]:
grid = np.random.randint(10, size=(3,3))
grid

array([[6, 0, 1],
       [4, 1, 7],
       [0, 2, 5]])

#### Present grid to user

In [3]:
print("Welcome to Shuffle! Here are your numbers...\n")
for i in grid:
    print(i)

print("\nShuffling grid...")


Welcome to Shuffle! Here are your numbers...

[6 0 1]
[4 1 7]
[0 2 5]

Shuffling grid...


#### Shuffle grid

In [4]:
random.shuffle(grid[0])
random.shuffle(grid[1])
random.shuffle(grid[2])
grid

array([[0, 1, 6],
       [4, 7, 1],
       [2, 0, 5]])

#### Get users column selection

In [5]:
print("The grid is now shuffled!")

The grid is now shuffled!


In [6]:
column = int(input("Pick a column: "))
column = column - 1

Pick a column: 2


In [7]:
row = int(input("pick a row:"))
row = row -1 

pick a row:3


In [8]:
guess = int(input("guess the number: "))

guess the number: 0


In [9]:
# Run the game...
if(grid[row][column] == guess):
    print("Correct! You guessed the number was {one} correctly".format(one=guess))
else:
    print("Try again...")
    guess = int(input("guess the number:"))

Correct! You guessed the number was 0 correctly
